.nh
.TH "GH-CODESPACE-DELETE" "1" "Mar 2022" "GitHub CLI 2.7.0" "GitHub CLI manual"

.SH NAME
.PP
gh-codespace-delete - Delete a codespace


.SH SYNOPSIS
.PP
\fB\fCgh codespace delete [flags]\fR


.SH OPTIONS
.TP
\fB\fC--all\fR
Delete all codespaces

.TP
\fB\fC-c\fR, \fB\fC--codespace\fR \fB\fC<string>\fR
Name of the codespace

.TP
\fB\fC--days\fR \fB\fC<N>\fR
Delete codespaces older than N days

.TP
\fB\fC-f\fR, \fB\fC--force\fR
Skip confirmation for codespaces that contain unsaved changes

.TP
\fB\fC-r\fR, \fB\fC--repo\fR \fB\fC<repository>\fR
Delete codespaces for a repository


.SH SEE ALSO
.PP
\fB\fCgh-codespace(1)\fR
