.nh
.TH "GH-CODESPACE-STOP" "1" "Mar 2022" "GitHub CLI 2.7.0" "GitHub CLI manual"

.SH NAME
.PP
gh-codespace-stop - Stop a running codespace


.SH SYNOPSIS
.PP
\fB\fCgh codespace stop [flags]\fR


.SH OPTIONS
.TP
\fB\fC-c\fR, \fB\fC--codespace\fR \fB\fC<string>\fR
Name of the codespace


.SH SEE ALSO
.PP
\fB\fCgh-codespace(1)\fR
