.nh
.TH "GH-LABEL-LIST" "1" "Mar 2022" "GitHub CLI 2.7.0" "GitHub CLI manual"

.SH NAME
.PP
gh-label-list - List labels in a repository


.SH SYNOPSIS
.PP
\fB\fCgh label list [flags]\fR


.SH DESCRIPTION
.PP
Display labels in a GitHub repository.


.SH OPTIONS
.TP
\fB\fC-L\fR, \fB\fC--limit\fR \fB\fC<int>\fR
Maximum number of items to fetch

.TP
\fB\fC-w\fR, \fB\fC--web\fR
List labels in the web browser


.SH OPTIONS INHERITED FROM PARENT COMMANDS
.TP
\fB\fC-R\fR, \fB\fC--repo\fR \fB\fC<[HOST/]OWNER/REPO>\fR
Select another repository using the [HOST/]OWNER/REPO format


.SH SEE ALSO
.PP
\fB\fCgh-label(1)\fR
