.nh
.TH "GH-REPO-CLONE" "1" "Mar 2022" "GitHub CLI 2.7.0" "GitHub CLI manual"

.SH NAME
.PP
gh-repo-clone - Clone a repository locally


.SH SYNOPSIS
.PP
\fB\fCgh repo clone <repository> [<directory>] [-- <gitflags>...]\fR


.SH DESCRIPTION
.PP
Clone a GitHub repository locally.

.PP
If the "OWNER/" portion of the "OWNER/REPO" repository argument is omitted, it
defaults to the name of the authenticating user.

.PP
Pass additional 'git clone' flags by listing them after '--'.


.SH SEE ALSO
.PP
\fB\fCgh-repo(1)\fR
